Open figures via the context menu
mathworks/MATLAB-extension-for-vscode pull request #157
Opened 2024-06-22 07:11 UTC by DFriend01

Resolves #156

2024-06-22 23:13 UTC, DFriend01 commented
Sorry for the mess, squashing commits went wrong :-)

2024-06-27 18:31 UTC, dklilley commented
Thank you for the pull request! I will take a look at it next week.

2024-07-02 13:59 UTC, dklilley requested changes
This looks good to me! Thank you for adding this!
Can you add an entry to the changelog about this feature?

2024-07-02 15:10 UTC, nothans commented
Can you contact me about signing a CLA? Thank you.

2024-07-02 16:51 UTC, DFriend01 commented
@nothans I sent you an email

2024-07-02 17:03 UTC, dklilley commented on CHANGELOG.md
> +- Enabled users to open MATLAB .fig files through the context menu
Can you move this under the existing `### Added` section?

2024-07-03 00:17 UTC, closed without merging

2024-11-07 17:34 UTC, Gusmano-2-OSU commented
Why wasn't this merged into main?